- title: Global Land Use and Land Cover Classification
  description:
    Impact Observatory used the Planetary Computer to build a global land use and
    land cover map at 10-meter resolution, by applying machine learning tools to
    satellite imagery.  The resulting map – which is now publicly available on the
    Planetary Computer – will support ecosystem monitoring and land use planning.
  thumbnailUrl: ./images/apps/io-lulc-wide-fs8.jpg
  links:
    - title: Explore land classification
      url: https://www.impactobservatory.com/lulc_map
    - title: Learn about Impact Observatory
      url: https://www.impactobservatory.com/

- title: Ecosystem Monitoring
  description:
    The Analytics Lab team at Conservation Science Partners (CSP) is using the
    Planetary Computer to monitor forest change, habitat connectivity, and the
    impacts of human land use across the U.S., providing a range of project partners
    and stakeholders with the data they need to make better conservation decisions in
    near real time.
  thumbnailUrl: ./images/apps/csp-wide-fs8.jpg
  links:
    - title: Explore ecosystem monitoring
      url: https://aka.ms/CSPapplication
    - title: Learn about CSP
      url: https://www.csp-inc.org/

- title: Conservation Planning
  description:
    The Nature Conservancy is using the Planetary Computer to protect and manage
    land, oceans, and biodiversity. In partnership with Microsoft and with
    development support from Vizzuality, TNC is accelerating conservation with
    Marxan, a cloud-based platform for data-driven spatial planning.
  thumbnailUrl: ./images/apps/marxan-wide-fs8.jpg
  links:
    - title: Explore conservation planning
      url: http://aka.ms/marxanonazure
    - title: Learn about The Nature Conservancy
      url: https://www.nature.org/

- title: Forest Carbon Risk Assessment
  description:
    CarbonPlan is leveraging Planetary Computer resources to enable more transparent
    and scientifically rigorous evaluation of forest-based climate solutions. By
    shining a data-driven light on past and future carbon offset projects, this
    enables procurement programs to favor the highest-quality outcomes.
  thumbnailUrl: ./images/apps/carbonplan-wide-fs8.jpg
  links:
    - title: Explore forest carbon map
      url: https://carbonplan.org/research/forest-risks
    - title: Learn about CarbonPlan
      url: https://carbonplan.org/

- title: AI-Accelerated Land Cover Mapping
  description:
    Development Seed is using the Planetary Computer to accelerate the critical work
    of the environmental scientists tasked with mapping the world's land use.  By
    combining Earth observation data and machine learning, this work is helping
    scientists spend more time planning conservation, and less time annotating
    imagery.
  thumbnailUrl: ./images/apps/azure-land-cover-fs8.jpg
  links:
    - title: Explore land cover mapping
      url: https://aka.ms/ai4e-landcover-app
    - title: Learn about Development Seed
      url: https://developmentseed.org/
