# Use STAC collection IDs to attach specific notebooks/content to a collection
# detail page.

# ****************************************************************************
# Any references to Notebook html files below require the .ipynb
# file to be included in the `etl/codefiles_urls.txt` file for processing
# ****************************************************************************

# Omitting headerImg will reuse and stretch the collection thumbnail

# `category` attribute determines which header the dataset is included under in the
# Explorer collection selector

# To include a button on a tab to launch the notebook in Hub, add the following
# config to the tab item. Assumes PlanetaryComputerExamples/main.

# tabs:
#   - title: My title
#     src: notebook.html
#     launch: tutorials/notebook.ipynb
#
# or, if you need to specify a different repo or branch, the full config is:
#
# tabs:
#   - title: My title
#     src: notebook.html
#     launch:
#       repo: http://github.com/exampleorg/myrepo
#       branch: v1
#       filePath: tutorials/notebook.ipynb

---
collections:
  alos-dem:
    category: DEMs
    headerImg: ./images/alos-hero.png
    tabs:
      - title: Example Notebook
        src: alos-dem-example.html
        launch: datasets/alos-dem/alos-dem-example.ipynb

  cop-dem-glo-90:
    category: DEMs

  cop-dem-glo-30:
    category: DEMs

  goes-fdc:
    category: Fire

  goes-rrqpe:
    category: Climate/Weather

  goes-cmi:
    category: Imagery

  goes-mcmip:
    category: Imagery

  goes-sst:
    category: Climate/Weather

  goes-lst:
    category: Climate/Weather

  3dep-seamless:
    category: DEMs
    headerImg: ./images/threedep-seamless-hero.png
    tabs:
      - title: Example Notebook
        src: 3dep-seamless-example.html
        launch: datasets/dep/3dep-seamless-example.ipynb

  daymet-daily-pr:
    headerImg: ./images/daymet-daily-pr-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-monthly-pr:
    headerImg: ./images/daymet-monthly-pr-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-annual-pr:
    headerImg: ./images/daymet-annual-pr-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-daily-hi:
    headerImg: ./images/daymet-daily-hi-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-monthly-hi:
    headerImg: ./images/daymet-monthly-hi-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-annual-hi:
    headerImg: ./images/daymet-annual-hi-hero.png
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-daily-na:
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-monthly-na:
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  daymet-annual-na:
    tabs:
      - title: Example Notebook
        src: daymet-example.html
        launch: datasets/daymet/daymet-example.ipynb

  gap:
    category: Land use/Land cover
    headerImg: ./images/gap-hero.png
    tabs:
      - title: Example Notebook
        src: gap-example.html
        launch: datasets/gap/gap-example.ipynb

  hgb:
    category: Biodiversity
    headerImg: ./images/hgb-hero.png
    tabs:
      - title: Example Notebook
        src: hgb-example.html
        launch: datasets/hgb/hgb-example.ipynb
      - title: Blob Storage Notebook
        src: hgb.html
      - title: Storage Documentation
        src: hgb-storage.html

  hrea:
    category: Infrastructure
    headerImg: ./images/hrea-hero.png
    tabs:
      - title: Example Notebook
        src: hrea-example.html
        launch: datasets/hrea/hrea-example.ipynb
      - title: Blob Storage Notebook
        src: hrea.html
      - title: Storage Documentation
        src: hrea-storage.html

  io-lulc:
    category: Land use/Land cover
    tabs:
      - title: Example Notebook
        src: io-lulc-example.html
        launch: datasets/io-lulc/io-lulc-example.ipynb
      - title: Storage Documentation
        src: io-lulc-storage.html

  jrc-gsw:
    category: Water
    headerImg: ./images/jrc-gsw-hero.png
    tabs:
      - title: Example Notebook
        src: jrc-gsw-example.html
        launch: datasets/jrc-gsw/jrc-gsw-example.ipynb

  mobi:
    category: Biodiversity
    headerImg: ./images/mobi-hero.png
    tabs:
      - title: Example Notebook
        src: mobi-example.html
        launch: datasets/mobi/mobi-example.ipynb
      - title: Blob Storage Notebook
        src: mobi.html
      - title: Storage Documentation
        src: mobi-storage.html

  mtbs:
    category: Fire
    headerImg: ./images/mtbs-hero.png
    tabs:
      - title: Example Notebook
        src: mtbs-example.html
        launch: datasets/mtbs/mtbs-example.ipynb
      - title: Blob Storage Notebook
        src: mtbs.html
      - title: Storage Documentation
        src: mtbs-storage.html

  nasadem:
    category: DEMs
    headerImg: ./images/nasadem-hero.png
    tabs:
      - title: Example Notebook
        src: nasadem-example.html
        launch: datasets/nasadem/nasadem-example.ipynb
      - title: Blob Storage Notebook
        src: nasadem-cog.html
      - title: Storage Documentation
        src: nasadem-storage.html

  terraclimate:
    category: Climate/Weather
    headerImg: ./images/terraclimate-hero.png
    tabs:
      - title: Example Notebook
        src: terraclimate-example.html
        launch: datasets/terraclimate/terraclimate-example.ipynb
      - title: Blob Storage Notebook
        src: terraclimate.html

  us-census:
    headerImg: ./images/us-census-hero.png
    tabs:
      - title: Example Notebook
        src: us-census-example.html
        launch: datasets/us-census/us-census-example.ipynb

  gbif:
    headerImg: ./images/gbif-hero.png
    tabs:
      - title: Example Notebook
        src: gbif-example.html
        launch: datasets/gbif/gbif-example.ipynb

  gridmet:
    headerImg: ./images/gridmet-hero.png
    tabs:
      - title: Example Notebook
        src: gridmet-example.html
        launch: datasets/gridmet/gridmet-example.ipynb

  fia:
    headerImg: ./images/fia-hero.png
    tabs:
      - title: Example Notebook
        src: fia-example.html
        launch: datasets/fia/fia-example.ipynb

  naip:
    category: Imagery
    headerImg: ./images/naip-hero.jpg
    tabs:
      - title: Example Notebook
        src: naip-example.html
        launch: datasets/naip/naip-example.ipynb
      - title: Blob Storage Notebook
        src: naip.html
      - title: Storage Documentation
        src: naip-storage.html

  landsat-8-c2-l2:
    category: Imagery
    headerImg: ./images/landsat-hero.jpg
    tabs:
      - title: Example Notebook
        src: landsat-8-c2-l2-example.html
        launch: datasets/landsat-8-c2-l2/landsat-8-c2-l2-example.ipynb
      - title: Blob Storage Notebook
        src: landsat-8.html
      - title: Storage Documentation
        src: landsat-8-storage.html

  sentinel-2-l2a:
    category: Imagery
    headerImg: ./images/sentinel-hero.jpg
    tabs:
      - title: Example Notebook
        src: sentinel-2-l2a-example.html
        launch: datasets/sentinel-2-l2a/sentinel-2-l2a-example.ipynb
      - title: Blob Storage Notebook
        src: sentinel-2.html
      - title: Storage Documentation
        src: sentinel-2-storage.html

  aster-l1t:
    category: Imagery
    headerImg: ./images/aster-hero.jpg
    tabs:
      - title: Example Notebook
        src: aster-l1t-example.html
        launch: datasets/aster-l1t/aster-l1t-example.ipynb
      - title: Blob Storage Notebook
        src: aster.html
      - title: Storage Documentation
        src: aster-storage.html

# Configuration for "other dataset" section. This list is rendered
# in the order represented here, which is mostly alphabetical, with
# some custom prioritization.
ai4e:
  - title: Deltares Global Flood Maps
    shortTerm: Deltares flood
    description: Global coastal inundation maps at multiple resolutions
    infoUrl: https://aka.ms/ai4edata-deltares-gfm
    thumbnailUrl: deltares-flood.png
    alt: Flood map of coastal Myanmar
    keywords: [Global, Flood, Sea level rise, Water]

  - title: Global Hydro Estimator
    shortTerm: global precipitation
    description: Global precipitation estimates
    infoUrl: http://aka.ms/ai4edata-ghe
    thumbnailUrl: RE4ucH7.jpg
    alt: Clouds at sunset
    keywords: [NOAA, Global, Precipitation]

  - title: GOES-16
    shortTerm: GOES-16 weather
    description: Weather imagery of the Americas
    infoUrl: http://aka.ms/ai4edata-goes16
    thumbnailUrl: RE4ucH9.jpg
    alt: Raindrops hitting water
    keywords: [GOES, Weather, Americas, Imagery]

  - title: Harmonized Landsat Sentinel-2
    shortTerm: HLS
    description: 30m-resolution satellite imagery for North America
    infoUrl: http://aka.ms/ai4edata-hls
    thumbnailUrl: RE3OM3E.jpg
    alt: Map of Chesapeake Bay
    keywords: [Landsat, Sentinel, Satellite, Imagery, North America]

  - title: LILA BC
    shortTerm: LILA BC
    description: Labeled images related to wildlife conservation
    infoUrl: http://lila.science/
    thumbnailUrl: RE3BWhq.jpg
    alt: Fox pup stands on a rock.
    keywords: [LILA, Labels, Wildlife, Biodiversity]

  - title: MODIS
    shortTerm: MODIS
    description:
      Satellite imagery from the Moderate Resolution Imaging Spectroradiometer
      (MODIS)
    infoUrl: https://aka.ms/ai4edata-modis
    thumbnailUrl: RE3BTDt.jpg
    alt: View of Earth from space.
    keywords: [MODIS, Satellite, Imagery, Global]

  - title: National Land Cover Database
    shortTerm: land cover
    description: US-wide data on land cover and land cover change
    infoUrl: https://aka.ms/ai4edata-nlcd
    thumbnailUrl: RWz0Zh.jpg
    alt: Landcover map of the United States
    keywords: [Land Cover, United States]

  - title: NOAA Global Forecast System
    shortTerm: NOAA global forecast
    description: 15-day US hourly weather forecast data
    infoUrl: https://aka.ms/ai4edata-gfs
    thumbnailUrl: RE4rvnx.jpg
    alt: Earth viewed from space station with a satellite
    keywords: [Global, NOAA, Weather, Temperature, Precipitation]

  - title: NOAA GFS Warm Start Conditions
    shortTerm: NOAA warm start
    description: Six-hourly initial conditions for the NOAA Global Forecast System
    infoUrl: https://aka.ms/ai4edata-gfs-warm-start
    thumbnailUrl: RE4MHyn.jpg
    alt: High altitude view of cloud cover with moon
    keywords: [Global, NOAA, Weather, Temperature, Precipitation]

  - title: NOAA Integrated Surface Data
    shortTerm: NOAA surface
    description: Worldwide hourly weather history data
    infoUrl: https://aka.ms/ai4edata-isd
    thumbnailUrl: RE4rsOQ.jpg
    alt: High altitude view of clouds
    keywords: [Global, NOAA, Weather, Temperature, Precipitation]

  - title: Ocean Observatories Initiative CAMHD
    shortTerm: OOI
    description: High-resolution video from the floor of the Pacific Ocean
    infoUrl: https://aka.ms/ai4edata-ooi-camhd
    thumbnailUrl: RE4KiKZ.jpg
    alt: Image from ocean floor video
    keywords: [OOI, Video, Ocean, Pacific]

  - title: Sentinel-1 GRD
    shortTerm: Sentinel-1 GRD
    description: Global synthetic aperture radar (SAR) data from 2017-present
    infoUrl: https://aka.ms/ai4edata-sentinel-1
    thumbnailUrl: sentinel-1-grd.jpg
    alt: False color rendering of Sentinel-1 GRD data near Seattle, WA, USA
    keywords: [Global, Sentinel, Satellite, ESA, SAR, Radar]

  - title: Sentinel-3 L2
    shortTerm: Sentinel-3 L2
    description:
      Global multispectral imagery at a resolution of 300m-500m from 2016-present
    infoUrl: https://github.com/microsoft/AIforEarthDataSets#sentinel-3-l2
    thumbnailUrl: sentinel-3-l2.png
    alt: Satellite image of Grand Canyon from Sentinel-3 L2
    keywords: [Global, Sentinel, Satellite, ESA, Temperature, SAR, Ocean, Imagery]

  - title: UK Met Office CSSP China 20CRDS
    shortTerm: CSSP China 20CRDS
    description: Historical climate data for China, from 1851-2010
    infoUrl: https://aka.ms/ai4edata-uk-met-20crds
    thumbnailUrl: cssp-china.jpg
    alt: Sky and clouds over mountain range
    keywords: [China, Climate, Historical]

