# Metadata for a "group" page, which consolidates related collections.
# `description` property accepts markdown

3dep-lidar:
  title: USGS 3DEP Lidar Collection
  short_description:
    Elevation data as 3D point clouds and derived Cloud Optimized GeoTIFFs using data
    from the USGS 3D Elevation Program.

  description: >
    To respond to growing needs for high-quality elevation data, the goal of 3DEP is to
    complete acquisition of nationwide lidar (IfSAR in AK) to provide the first-ever
    national baseline of consistent high-resolution topographic elevation data –
    both bare earth and 3D point clouds.

    This dataset provides the raw 3D point clouds in the
    [Cloud Optimized Point Cloud](https://copc.io/) format, and various derived products
    as [Cloud Optimized GeoTIFFs](https://www.cogeo.org/).
  assets:
    headerImg:
      href: ./images/3dep-lidar-copc-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/3dep-lidar-copc-thumbnail.png
  keywords: [USGS, 3DEP, Elevation, Lidar, Point Cloud]

daymet:
  title: Daymet Collection
  short_description:
    Gridded estimates of weather parameters for North America, Hawaii, and Puerto
    Rico at daily, monthly, and annual temporal resolutions
  description: >
    [Daymet](https://daymet.ornl.gov) provides long-term, continuous, gridded
    estimates of daily weather and climatology variables by interpolating and
    extrapolating ground-based observations through statistical modeling techniques.
    Daymet data products have applications in Earth science, natural resource
    management, biodiversity conservation, and agricultural research.


    Daymet weather variables include daily minimum and maximum temperature,
    precipitation, vapor pressure, shortwave radiation, snow water equivalent, and
    day length.  All variables are produced on a 1 km x 1 km gridded surface, and are
    available from 1980 to the end of the most recent calendar year.
  assets:
    headerImg:
      href: ./images/daymet-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/daymet-na.jpg
  keywords: [Daymet, Weather, Climate, North America, Puerto Rico, Hawaii]

cil-gdpcir:
  title: CIL Global Downscaled Projections for Climate Impacts Research
  short_description:
    Climate Impact Lab Global Downscaled Projections for Climate Impacts Research

  description: >
    Climate Impact Lab Global Downscaled Projections for Climate Impacts Research
  assets:
    headerImg:
      href: ./images/cil-gdpcir.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/gdpcir.png
  keywords: [CMIP6, Climate Impact Lab, Rhodium Group, Precipitation, Temperature]

copernicus-dem:
  title: Copernicus DEM Collection
  short_description:
    Copernicus DEM is a near-global digital surface model (DSM) derived from radar
    satellite data acquired during the TanDEM-X mission.
  description: >
    The Copernicus DEM is a digital surface model (DSM), which represents the surface
    of the Earth including buildings, infrastructure, and vegetation. This DSM is
    based on radar satellite data acquired during the TanDEM-X Mission, which was
    funded by a public-private partnership between the German Aerospace Centre (DLR)
    and Airbus Defence and Space.  Copernicus DEM is available at both 30-meter and
    90-meter resolution.
  assets:
    headerImg:
      href: ./images/cop-dem-collection-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/cop-dem.png
  keywords: [Copernicus, DEM, DSM, elevation]

io-land-cover:
  title: 10 meter Land Cover
  short_description: Global land use/land cover information at 10m resolution
  description: >
    Global estimates of land use/land cover (LULC), derived from ESA Sentinel-2
    imagery at 10m resolution. This dataset was generated by [Impact
    Observatory](http://impactobservatory.com/), who used billions of human-labeled
    pixels (curated by the National Geographic Society) to train a deep learning
    model for land classification. The global maps were produced by applying this
    model to the Sentinel-2 scene collection on the Planetary Computer.


    All of the annual LULC datasets are available under a Creative Commons BY-4.0
    license.

  assets:
    headerImg:
      href: ./images/io-lulc-group-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/io-lulc.png
  keywords: [Global, Land Cover, Land Use, Sentinel]

gnatsgo:
  title: gNATSGO Soil Database
  short_description:
    The gridded National Soil Survey Geographic Database (gNATSGO) is a USDA-NRCS
    Soil & Plant Science Division (SPSD) composite database that provides complete
    coverage of the best available soils information for all areas of the United
    States and Island Territories
  description: >
    The gridded National Soil Survey Geographic Database (gNATSGO) is a USDA-NRCS
    Soil & Plant Science Division (SPSD) composite database that provides complete
    coverage of the best available soils information for all areas of the United
    States and Island Territories. It was created by combining data from the Soil
    Survey Geographic Database (SSURGO), State Soil Geographic Database (STATSGO2),
    and Raster Soil Survey Databases (RSS) into a single seamless ESRI file
    geodatabase.


    SSURGO is the SPSD flagship soils database that has over 100 years of
    field-validated detailed soil mapping data. SSURGO contains soils information for
    more than 90 percent of the United States and island territories, but unmapped
    land remains. STATSGO2 is a general soil map that has soils data for all of the
    United States and island territories, but the data is not as detailed as the
    SSURGO data. The Raster Soil Surveys (RSSs) are the next generation soil survey
    databases developed using advanced digital soil mapping methods.


    The gNATSGO database is composed primarily of SSURGO data, but STATSGO2 data was
    used to fill in the gaps. The RSSs are newer product with relatively limited
    spatial extent. These RSSs were merged into the gNATSGO after combining the
    SSURGO and STATSGO2 data. The extent of RSS is expected to increase in the coming
    years.


    See the [official
    documentation](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcseprd1464625).
  assets:
    headerImg:
      href: ./images/gnatsgo-rasters-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/gnatsgo-rasters.png
  keywords: [Soils, SSURGO, USDA]

modis:
  title: MODIS Version 6.1 Products
  short_description: >
    The Moderate Resolution Imaging Spectroradiometer (MODIS) instrument operates on both the
    Terra and Aqua spacecraft. The instrument has a swath width of 2,330 km and covers the entire
    surface of the Earth within one or two days. The data products derived from MODIS observations 
    describe atmosphere, cryosphere, land, and ocean features utilized in studies across various disciplines. 
  description: >
    The Moderate Resolution Imaging Spectroradiometer (MODIS) instrument operates on both the
    [Terra](http://terra.nasa.gov/) and [Aqua](http://aqua.nasa.gov/) spacecraft. The instrument 
    has a swath width of 2,330 km and covers the entire surface of the Earth within one or two days. 
    The sensor measures 36 spectral bands between 0.405-14.385 µm and acquires data at three
    spatial resolutions: 250, 500, and 1,000 m.


    MODIS Collection 6.1 (061) processing began in September 2017. The release incorporates 
    improvements and changes to the Level-1B (L1B) products utilized as inputs for higher 
    level products. MODIS Collection 6.1 products are available at Level 3 and 4 for land 
    and cryosphere products. Each product type is combined into a single collection in the 
    Planetary Computer. Additional information is provided on each collection's homepage. 
  assets:
    headerImg:
      href: ./images/modis-11A1-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/modis-11A1-061.png
  keywords:
    [
      MODIS,
      NASA,
      USGS,
      Satellite,
      Global,
      Imagery,
      Reflectance,
      Temperature,
      Land Cover,
    ]

landsat:
  title: Landsat Collection
  short_description: >
    The Landsat program provides provides a comprehensive, continuous archive of
    multispectral imagery of the Earth's surface from 1972 to present.
  description: >
    The [Landsat](https://landsat.gsfc.nasa.gov/) program has been imaging the
    Earth since 1972, providing a comprehensive, continuous archive of the
    Earth's surface. This dataset represents a global archive of
    [Level-1](https://www.usgs.gov/landsat-missions/landsat-collection-2-level-1-data)
    and [Level-2](https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products)
    Landsat data from [Landsat Collection 2](https://www.usgs.gov/landsat-missions/landsat-collection-2).


    Collection 2 Level-1 data is provided for imagery acquired by the
    Multispectral Scanner System (MSS) onboard Landsat 1 through Landsat 5 from
    July 1972 to January 2013. Collection 2 Level-2 data is provided for imagery
    acquired by the Thematic Mapper (TM) onboard Landsat 4 and 5, the Enhanced
    Thematic Mapper Plus (ETM+) onboard Landsat 7, and the Operational Land
    Imager (OLI) and Thermal Infrared Sensor (TIRS) onboard Landsat 8 and 9.
    Collection 2 Level-2 data is available from August 1982 to present. All
    images are stored in [cloud-optimized GeoTiff](https://www.cogeo.org/)
    format.
  assets:
    headerImg:
      href: ./images/landsat-hero.jpg
    thumbnail:
      href: "https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/landsat.png"
  keywords:
    [
      "Landsat",
      "USGS",
      "NASA",
      "Satellite",
      "Global",
      "Imagery",
      "Reflectance",
      "Temperature",
    ]

planet-nicfi:
  title: Planet-NICFI Collection
  short_description: >
    Planet's high-resolution, analysis-ready mosaics of the world's tropics
  description: >
    Through Norway's International Climate & Forests Initiative (NICFI), users can access [Planet's](https://www.planet.com/) high-resolution, analysis-ready mosaics of the world's tropics in order to help reduce and reverse the loss of tropical forests, combat climate change, conserve biodiversity, and facilitate sustainable development.

  assets:
    headerImg:
      href: ./images/planet-nicfi-visual-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/nicfi_tropics_basemap_map_d1.jpg
  keywords:
    [
      "Planet",
      "NICFI",
      "Satellite",
      "Tropics",
      "Imagery"
    ]

sentinel-1:
  title: Sentinel-1 Synthetic Aperture Radar (SAR)
  short_description: >
    Sentinel-1 comprises a constellation of two polar-orbiting satellites, operating day and night performing C-band synthetic aperture radar imaging.
  description: >
    [Sentinel 1](https://sentinel.esa.int/web/sentinel/missions/sentinel-1) is an imaging radar mission conducted by the European Space Agency providing continuous all-weather, day-and-night imagery at C-band.
    The Sentinel-1 constellation provides high reliability, improved revisit time, geographical coverage and rapid data dissemination to support operational
    applications in the priority areas of marine monitoring, land monitoring and emergency services.


    See the [Sentinel-1 documentation](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/overview) on the ESA's site
    for more information about the mission and products.
  assets:
    headerImg:
      href: ./images/sentinel-1-hero.png
    thumbnail:
      href: "https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/sentinel-1.png"
  keywords: ["ESA", "Copernicus", "Sentinel", "C-Band", "SAR"]

chesapeake-lulc:
  title: Chesapeake Land Use Land Cover
  short_description: >
    Land Use and Land Cover maps for the Chesapeake Bay Watershed from the Conservation Innovation Center at the Chesapeake Conservancy.
  description: >
    One-meter resolution land use and land cover maps for the entire Chesapeake Bay watershed, an area of over 250,000 square kilomters that spans New York, Pennsylvania, Maryland, Delaware, West Virginia, Virginia, and the District of Columbia. The data are made available by the [Conservation Innovation Center](https://www.chesapeakeconservancy.org/conservation-innovation-center/) at the [Chesapeake Conservancy](https://www.chesapeakeconservancy.org/). Based on 2013-2014 imagery from the National Agriculture Imagery Program, the high resolution classification data provides 900 times the amount of information as conventional 30-meter land cover data that has traditionally been utilized for this area.
  assets:
    headerImg:
      href: ./images/chesapeake-lulc-hero.png
    thumbnail:
      href: "https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/chesapeake-lulc-thumb.png"
  keywords:
    [
      "Land Use",
      "Land Cover",
      "Chesapeake Bay Watershed",
      "Chesapeake Conservancy"
    ]