# Metadata for a "group" page, which consolidates related collections.
# `description` property accepts markdown

daymet:
  title: Daymet Collection
  short_description:
    Gridded estimates of weather parameters for North America, Hawaii, and Puerto
    Rico at daily, monthly, and annual summaries
  description: >
    Daymet provides long-term, continuous, gridded estimates of daily weather and
    climatology variables by interpolating and extrapolating ground-based
    observations through statistical modeling techniques. The
    [Daymet](https://daymet.ornl.gov/overview) data products provide driver data for
    biogeochemical terrestrial modeling and have myriad applications in many Earth
    science, natural resource, biodiversity, and agricultural research areas.


    Daymet weather variables include daily minimum and maximum temperature,
    precipitation, vapor pressure, shortwave radiation, snow water equivalent, and
    day length produced on a 1 km x 1 km gridded surface over continental North
    America, Hawaii, and Puerto Rico from 1980 through the end of the most recent
    full calendar year.
  assets:
    headerImg:
      href: ./images/daymet-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/daymet-na.jpg
  keywords: [Daymet, Weather, Climate, North America, Puerto Rico, Hawaii]

goes:
  title: GOES Collection
  short_description: TBD.
  description: TBD.
  assets:
    headerImg:
      href: https://via.placeholder.com/550x100?text=Placeholder...
    thumbnail:
      href: https://via.placeholder.com/550x300?text=Placeholder...
  keywords: [GOES, Global, Satellite, Imagery, Fire, Weather, Climate, Ocean]

copernicus-dem:
  title: Copernicus DEM Collection
  short_description: This data set is a global digital surface model (DSM) with horizontal resolution of either 30 or 90 meters derived from an edited DSM named WorldDEMTM based on radar satellite data aquired during the TanDEM-X Mission 
  description: >
    The Copernicus DEM is a Digital Surface Model (DSM) which represents the surface of the Earth including buildings, infrastructure and vegetation. This DEM is derived from an edited DSM named WorldDEMTM, i.e. flattening of water bodies and consistent flow of rivers has been included. Editing of shore- and coastlines, special features such as airports and implausible terrain structures has also been applied.

    The WorldDEM product is based on the radar satellite data acquired during the TanDEM-X Mission, which is funded by a Public Private Partnership between the German State, represented by the German Aerospace Centre (DLR) and Airbus Defence and Space.

  assets:
    headerImg:
      href: ./images/cop-dep-collection-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/cop-dem.png
  keywords: [Copernicus, DEM, DSM, elevation]



