# Metadata for a "group" page, which consolidates related collections.
# `description` property accepts markdown

daymet:
  title: Daymet Collection
  short_description:
    Gridded estimates of weather parameters for North America, Hawaii, and Puerto
    Rico at daily, monthly, and annual temporal resolutions
  description: >
    [Daymet](https://daymet.ornl.gov) provides long-term, continuous, gridded estimates of 
    daily weather and climatology variables by interpolating and extrapolating ground-based
    observations through statistical modeling techniques. Daymet data products have 
    applications in Earth science, natural resource management, biodiversity conservation,
    and agricultural research.    
        
    Daymet weather variables include daily minimum and maximum temperature,
    precipitation, vapor pressure, shortwave radiation, snow water equivalent, and
    day length.  All variables are produced on a 1 km x 1 km gridded surface, and are available 
    from 1980 to the end of the most recent calendar year.
  assets:
    headerImg:
      href: ./images/daymet-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/daymet-na.jpg
  keywords: [Daymet, Weather, Climate, North America, Puerto Rico, Hawaii]

copernicus-dem:
  title: Copernicus DEM Collection
  short_description: Copernicus DEM is a near-global digital surface model (DSM) derived from radar 
    satellite data acquired during the TanDEM-X mission. 
  description: >
    The Copernicus DEM is a digital surface model (DSM), which represents the surface of the Earth 
    including buildings, infrastructure, and vegetation. This DSM is based on radar satellite data 
    acquired during the TanDEM-X Mission, which was funded by a public-private partnership between 
    the German Aerospace Centre (DLR) and Airbus Defence and Space.  Copernicus DEM is available at both 
    30-meter and 90-meter resolution.
  assets:
    headerImg:
      href: ./images/cop-dem-collection-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/cop-dem.png
  keywords: [Copernicus, DEM, DSM, elevation]
io-lulc:
  title: Esri 10-meter Land Cover
  short_description: Global land cover information at 10m resolution
  description: >
    Global estimates of 10-class land use/land cover (LULC) for multiple years,
    derived from ESA Sentinel-2 imagery at 10m resolution. A 10 class and 9 class version
    are avaible. These dataset are generated by [Impact Observatory](http://impactobservatory.com/),
    who used billions of human-labeled pixels (curated by the National Geographic Society) to train
    a deep learning model for land classification.  The global map was produced by applying this model
    to the relevant yearly Sentinel-2 scenes on the Planetary Computer.
  assets:
    headerImg:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/io-lulc.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/io-lulc.png
  keywords: [Copernicus, DEM, DSM, elevation]
# Waiting on other GOES collections
# goes:
#   title: GOES Collection
#   short_description: TBD.
#   description: TBD.
#   assets:
#     headerImg:
#       href: https://via.placeholder.com/550x100?text=Placeholder...
#     thumbnail:
#       href: https://via.placeholder.com/550x300?text=Placeholder...
#   keywords: [GOES, Global, Satellite, Imagery, Fire, Weather, Climate, Ocean]
