# Metadata for a "group" page, which consolidates related collections.
# `description` property accepts markdown

daymet:
  title: Daymet Collection
  short_description:
    Gridded estimates of weather parameters for North America, Hawaii, and Puerto
    Rico at daily, monthly, and annual summaries
  description: >
    Daymet provides long-term, continuous, gridded estimates of daily weather and
    climatology variables by interpolating and extrapolating ground-based
    observations through statistical modeling techniques. The
    [Daymet](https://daymet.ornl.gov/overview) data products provide driver data for
    biogeochemical terrestrial modeling and have myriad applications in many Earth
    science, natural resource, biodiversity, and agricultural research areas.


    Daymet weather variables include daily minimum and maximum temperature,
    precipitation, vapor pressure, shortwave radiation, snow water equivalent, and
    day length produced on a 1 km x 1 km gridded surface over continental North
    America, Hawaii, and Puerto Rico from 1980 through the end of the most recent
    full calendar year.
  assets:
    headerImg:
      href: ./images/daymet-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/daymet-na.jpg
  keywords: [Daymet, Weather, Climate, North America, Puerto Rico, Hawaii]
