# Metadata for a "group" page, which consolidates related collections.
# `description` property accepts markdown

daymet:
  title: Daymet Collection
  short_description:
    Gridded estimates of weather parameters for North America, Hawaii, and Puerto
    Rico at daily, monthly, and annual temporal resolutions
  description: >
    [Daymet](https://daymet.ornl.gov) provides long-term, continuous, gridded
    estimates of daily weather and climatology variables by interpolating and
    extrapolating ground-based observations through statistical modeling techniques.
    Daymet data products have applications in Earth science, natural resource
    management, biodiversity conservation, and agricultural research.


    Daymet weather variables include daily minimum and maximum temperature,
    precipitation, vapor pressure, shortwave radiation, snow water equivalent, and
    day length.  All variables are produced on a 1 km x 1 km gridded surface, and are
    available from 1980 to the end of the most recent calendar year.
  assets:
    headerImg:
      href: ./images/daymet-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/daymet-na.jpg
  keywords: [Daymet, Weather, Climate, North America, Puerto Rico, Hawaii]

copernicus-dem:
  title: Copernicus DEM Collection
  short_description:
    Copernicus DEM is a near-global digital surface model (DSM) derived from radar
    satellite data acquired during the TanDEM-X mission.
  description: >
    The Copernicus DEM is a digital surface model (DSM), which represents the surface
    of the Earth including buildings, infrastructure, and vegetation. This DSM is
    based on radar satellite data acquired during the TanDEM-X Mission, which was
    funded by a public-private partnership between the German Aerospace Centre (DLR)
    and Airbus Defence and Space.  Copernicus DEM is available at both 30-meter and
    90-meter resolution.
  assets:
    headerImg:
      href: ./images/cop-dem-collection-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/cop-dem.png
  keywords: [Copernicus, DEM, DSM, elevation]

io-land-cover:
  title: 10 meter Land Cover
  short_description: Global land use/land cover information at 10m resolution
  description: >
    Global estimates of land use/land cover (LULC), derived from ESA Sentinel-2
    imagery at 10m resolution. This dataset was generated by [Impact
    Observatory](http://impactobservatory.com/), who used billions of human-labeled
    pixels (curated by the National Geographic Society) to train a deep learning
    model for land classification. The global maps were produced by applying this
    model to the Sentinel-2 scene collection on the Planetary Computer.


    All of the annual LULC datasets are available under a Creative Commons BY-4.0
    license.

  assets:
    headerImg:
      href: ./images/io-lulc-group-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/io-lulc.png
  keywords: [Global, Land Cover, Land Use, Sentinel]

gnatsgo:
  title: gNATSGO Soil Database
  short_description:
    The gridded National Soil Survey Geographic Database (gNATSGO) is a USDA-NRCS
    Soil & Plant Science Division (SPSD) composite database that provides complete
    coverage of the best available soils information for all areas of the United
    States and Island Territories
  description: >
    The gridded National Soil Survey Geographic Database (gNATSGO) is a USDA-NRCS
    Soil & Plant Science Division (SPSD) composite database that provides complete
    coverage of the best available soils information for all areas of the United
    States and Island Territories. It was created by combining data from the Soil
    Survey Geographic Database (SSURGO), State Soil Geographic Database (STATSGO2),
    and Raster Soil Survey Databases (RSS) into a single seamless ESRI file
    geodatabase.


    SSURGO is the SPSD flagship soils database that has over 100 years of
    field-validated detailed soil mapping data. SSURGO contains soils information for
    more than 90 percent of the United States and island territories, but unmapped
    land remains. STATSGO2 is a general soil map that has soils data for all of the
    United States and island territories, but the data is not as detailed as the
    SSURGO data. The Raster Soil Surveys (RSSs) are the next generation soil survey
    databases developed using advanced digital soil mapping methods.


    The gNATSGO database is composed primarily of SSURGO data, but STATSGO2 data was
    used to fill in the gaps. The RSSs are newer product with relatively limited
    spatial extent. These RSSs were merged into the gNATSGO after combining the
    SSURGO and STATSGO2 data. The extent of RSS is expected to increase in the coming
    years.


    See the [official
    documentation](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcseprd1464625).
  assets:
    headerImg:
      href: ./images/gnatsgo-rasters-hero.png
    thumbnail:
      href: https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/gnatsgo-rasters.png
  keywords: [Soils, SSURGO, USDA]

modis:
  title: MODIS Collection
  short_description: >
    TODO
  description: >
    TODO
  assets:
    headerImg:
      href: https://via.placeholder.com/1200x800
    thumbnail:
      href: https://via.placeholder.com/500x300?text=MODIS TODO
    keywords: ["MODIS", "TODO"]

landsat:
  title: Landsat Collection
  short_description: >
    The Landsat program provides provides a comprehensive, continuous archive of
    multispectral imagery of the Earth's surface from 1972 to present.
  description: >
    The [Landsat](https://landsat.gsfc.nasa.gov/) program has been imaging the
    Earth since 1972, providing a comprehensive, continuous archive of the
    Earth's surface. This dataset represents a global archive of
    [Level-1](https://www.usgs.gov/landsat-missions/landsat-collection-2-level-1-data)
    and [Level-2](https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products)
    Landsat data from [Landsat Collection 2](https://www.usgs.gov/landsat-missions/landsat-collection-2).


    Collection 2 Level-1 data is provided for imagery acquired from the
    Multispectral Scanner System (MSS) onboard Landsat 1 through Landsat 5 from
    July 1972 to January 2013. Collection 2 Level-2 data is provided for imagery
    acquired from the Thematic Mapper (TM) onboard Landsat 4 and 5, the Enhanced
    Thematic Mapper Plus (ETM+) onboard Landsat 7, and the Operational Land
    Imager (OLI) and Thermal Infrared Sensor (TIRS) onboard Landsat 8 and 9.
    Collection Level-2 data is available from August 1982 to present. All images
    are stored in [cloud-optimized GeoTiff](https://www.cogeo.org/) format.
  assets:
    headerImg:
      href: https://via.placeholder.com/1200x800
    thumbnail:
      href: "https://ai4edatasetspublicassets.blob.core.windows.net/assets/pc_thumbnails/landsat.png"
    keywords: ["Landsat", "USGS", "NASA", "Satellite", "Global", "Imagery", "Reflectance", "Temperature"]